Traceback (most recent call last):
  File "/home/josefine/miniconda3/envs/ck1310/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/josefine/miniconda3/envs/ck1310/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josefine/miniconda3/envs/ck1310/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josefine/miniconda3/envs/ck1310/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/josefine/miniconda3/envs/ck1310/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/josefine/miniconda3/envs/ck1310/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/josefine/miniconda3/envs/ck1310/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from openmm.app import *
from openmm import *
from openmm.unit import *
from sys import stdout

pdb = PDBFile('input.pdb')
forcefield = ForceField('amber14-all.xml', 'amber14/tip3pfb.xml')
system = forcefield.createSystem(pdb.topology, nonbondedMethod=PME,
        nonbondedCutoff=1*nanometer, constraints=HBonds)
integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.004*picoseconds)
simulation = Simulation(pdb.topology, system, integrator)
simulation.context.setPositions(pdb.positions)
simulation.minimizeEnergy()
simulation.reporters.append(PDBReporter('output.pdb', 1000))
simulation.reporters.append(StateDataReporter(stdout, 1000, step=True,
        potentialEnergy=True, temperature=True))
simulation.step(10000)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[1], line 6[0m
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mopenmm[39;00m[38;5;21;01m.[39;00m[38;5;21;01munit[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01msys[39;00m [38;5;28;01mimport[39;00m stdout
[0;32m----> 6[0m pdb [38;5;241m=[39m [43mPDBFile[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43minput.pdb[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      7[0m forcefield [38;5;241m=[39m ForceField([38;5;124m'[39m[38;5;124mamber14-all.xml[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mamber14/tip3pfb.xml[39m[38;5;124m'[39m)
[1;32m      8[0m system [38;5;241m=[39m forcefield[38;5;241m.[39mcreateSystem(pdb[38;5;241m.[39mtopology, nonbondedMethod[38;5;241m=[39mPME,
[1;32m      9[0m         nonbondedCutoff[38;5;241m=[39m[38;5;241m1[39m[38;5;241m*[39mnanometer, constraints[38;5;241m=[39mHBonds)

File [0;32m~/miniconda3/envs/ck1310/lib/python3.11/site-packages/openmm/app/pdbfile.py:93[0m, in [0;36mPDBFile.__init__[0;34m(self, file, extraParticleIdentifier)[0m
[1;32m     91[0m own_handle [38;5;241m=[39m [38;5;28;01mFalse[39;00m
[1;32m     92[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(file, [38;5;28mstr[39m):
[0;32m---> 93[0m     inputfile [38;5;241m=[39m [38;5;28;43mopen[39;49m[43m([49m[43mfile[49m[43m)[49m
[1;32m     94[0m     own_handle [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m     95[0m pdb [38;5;241m=[39m PdbStructure(inputfile, load_all_models[38;5;241m=[39m[38;5;28;01mTrue[39;00m, extraParticleIdentifier[38;5;241m=[39mextraParticleIdentifier)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'input.pdb'

